name: Kivy Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Kivy
        run: pip install kivy
      - name: Run tests
        run: python -m unittest discover -v
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Kivy
        run: pip install kivy
      - name: Deploy
        run: python setup.py sdist bdist_wheel
        shell: bash
      - name: Upload to PyPI
        run: twine upload dist/*
